### ISSUE TITLE
Echo bot example doesn't work

### ISSUE THREAD

**Issue by Yashko** [watzon/tourmaline#13]
Example code: https://github.com/watzon/tourmaline/blob/master/examples/echo_bot.cr

Error output:
```
5 | class EchoBot < Tourmaline::Client
                     ^-----------------
Error: undefined constant Tourmaline::Client
```

```
dependencies:
  tourmaline:
    github: watzon/tourmaline
    version: ~> 0.13.0
```
```
Crystal 0.33.0 [612825a53] (2020-02-14)

LLVM: 8.0.0
Default target: x86_64-unknown-linux-gnu
```
